# Generated by Django 5.1.3 on 2024-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('second_name', models.CharField(max_length=125)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
